Repository knoxite/knoxite, pull requests merged in 2020-09, with the labels that each got.

#150 Delete previously existing versions of a file before reuploading to Backblaze
  .github/workflows/test.yml
  storage/backblaze/backblaze.go
Labels: bug, storage backend, tests

#151 Fix issues with config `SetURL`
  config/config.go
  config/config_test.go
  go.mod
  utils/utils.go
Labels: bug, cli

#155 Retry storage operations three times in case of an error
  backendmanager.go
Labels: core, improvement

#164 Make clone command receive cli flags
  cmd/knoxite/clone.go
  cmd/knoxite/store.go
Labels: bug, cli

#165 Use `--alias | -R` flag instead of `--repository | -r` for aliases
  cmd/knoxite/main.go
  cmd/knoxite/repository.go
  cmd/knoxite/restore.go
  cmd/knoxite/store.go
Labels: cli, improvement

#166 Add 'volume remove' command
  cmd/knoxite/volume.go
  repository.go
Labels: cli, core, feature

#168 Add logo to README
  README.md
  assets/knoxite-logo.svg
Labels: documentation

#169 Combine all snapshot settings in a single struct called StoreOptions
  chunk.go
  chunkindex_test.go
  cmd/knoxite/store.go
  snapshot.go
  snapshot_test.go
  verify_test.go
Labels: core, improvement
