Repository knoxite/knoxite, pull requests merged in 2020-05, with the labels that each got.

#111 Added Version Flag
  cmd/knoxite/main.go
Labels: feature

#112 Fix upstream 404
  admin/setup_ftp_test_environment.sh
Labels: tests

#114 Make repository password independent of the encryption key
  chunkindex.go
  decode.go
  repository.go
  snapshot.go
Labels: core, feature, improvement

#115 Fixed Azure backend test
  .github/workflows/go.yml
  storage/azure/azure_file_test.go
Labels: bug, tests

#116 Added repo passwd command to change the password of a repository
  cmd/knoxite/repository.go
Labels: cli, feature, improvement
