Repository knoxite/knoxite, pull requests merged in 2020-08, with the labels that each got.

#142 Split build & test into separate workflows
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: tests

#140 Add new `convert` subcommand to `config` command
  cmd/knoxite/config.go
Labels: cli, feature

#139 Expand tilde to the users home directory
  config/config.go
Labels: improvement

#144 Add linter workflow
  .github/workflows/lint.yml
  .golangci.yml
Labels: improvement, tests

#109 GoogleCloud backend does now create a folder when initializing a repo if it does not exist yet
  storage/googlecloud/gcloud.go
Labels: storage backend

#146 Adding SpaceUnlimited error in backend.go
  backend.go
  storage/backblaze/backblaze.go
  storage/backendtester.go
  storage/googlecloud/gcloud.go
  storage/s3/s3.go
Labels: bug, tests

#98 Add demo recording script
  admin/demos/demo-base.sh
  admin/demos/demo-magic.sh
  admin/demos/demo_help.sh
  admin/demos/demo_tutorial.sh
  admin/demos/record_demos.sh
Labels: documentation
