Repository knoxite/knoxite, pull requests merged in 2021-12, with the labels that each got.

#199 clarify and clean up clone command
  README.md
  cmd/knoxite/clone.go
Labels: improvement, cli

#212 added argument completions to carapace
  cmd/knoxite/action/config.go
  cmd/knoxite/action/repo.go
  cmd/knoxite/action/repository.go
  cmd/knoxite/action/snapshot.go
  cmd/knoxite/action/volume.go
  cmd/knoxite/cat.go
  cmd/knoxite/clone.go
  cmd/knoxite/config.go
  cmd/knoxite/docs.go
  cmd/knoxite/ls.go
  cmd/knoxite/main.go
  cmd/knoxite/mount.go
  cmd/knoxite/repository.go
  cmd/knoxite/restore.go
  cmd/knoxite/snapshot.go
  cmd/knoxite/store.go
  cmd/knoxite/verify.go
  cmd/knoxite/volume.go
  go.mod
  go.sum
Labels: cli

#217 Re-introduce os.Exit after fatal logging
  cmd/knoxite/logger.go
Labels: bug
